curl -o 01.html https://oshoworld.com/sufis-the-people-of-path-vol-2-01/
curl -o 02.html https://oshoworld.com/sufis-the-people-of-path-vol-2-02/
curl -o 03.html https://oshoworld.com/sufis-the-people-of-path-vol-2-03/
curl -o 04.html https://oshoworld.com/sufis-the-people-of-path-vol-2-04/
curl -o 05.html https://oshoworld.com/sufis-the-people-of-path-vol-2-05/
curl -o 06.html https://oshoworld.com/sufis-the-people-of-path-vol-2-06/
curl -o 07.html https://oshoworld.com/sufis-the-people-of-path-vol-2-07/
curl -o 08.html https://oshoworld.com/sufis-the-people-of-path-vol-2-08/
curl -o 09.html https://oshoworld.com/sufis-the-people-of-path-vol-2-09/
curl -o 10.html https://oshoworld.com/sufis-the-people-of-path-vol-2-10/
curl -o 11.html https://oshoworld.com/sufis-the-people-of-path-vol-2-11/
curl -o 12.html https://oshoworld.com/sufis-the-people-of-path-vol-2-12/
curl -o 13.html https://oshoworld.com/sufis-the-people-of-path-vol-2-13/
curl -o 14.html https://oshoworld.com/sufis-the-people-of-path-vol-2-14/
curl -o 15.html https://oshoworld.com/sufis-the-people-of-path-vol-2-15/