curl -o 01.html https://oshoworld.com/sufis-the-people-of-path-vol-1-01/
curl -o 02.html https://oshoworld.com/sufis-the-people-of-path-vol-1-02/
curl -o 03.html https://oshoworld.com/sufis-the-people-of-path-vol-1-03/
curl -o 04.html https://oshoworld.com/sufis-the-people-of-path-vol-1-04/
curl -o 05.html https://oshoworld.com/sufis-the-people-of-path-vol-1-05/
curl -o 06.html https://oshoworld.com/sufis-the-people-of-path-vol-1-06/
curl -o 07.html https://oshoworld.com/sufis-the-people-of-path-vol-1-07/
curl -o 08.html https://oshoworld.com/sufis-the-people-of-path-vol-1-08/
curl -o 09.html https://oshoworld.com/sufis-the-people-of-path-vol-1-09/
curl -o 10.html https://oshoworld.com/sufis-the-people-of-path-vol-1-10/
curl -o 11.html https://oshoworld.com/sufis-the-people-of-path-vol-1-11/
curl -o 12.html https://oshoworld.com/sufis-the-people-of-path-vol-1-12/
curl -o 13.html https://oshoworld.com/sufis-the-people-of-path-vol-1-13/
curl -o 14.html https://oshoworld.com/sufis-the-people-of-path-vol-1-14/
curl -o 15.html https://oshoworld.com/sufis-the-people-of-path-vol-1-15/
curl -o 16.html https://oshoworld.com/sufis-the-people-of-path-vol-1-16/