curl -o author-s-note.html https://www.jkrishnamurti.org/content/author%E2%80%99s-note
curl -o 01.html https://www.jkrishnamurti.org/content/chapter-1
curl -o 02.html https://www.jkrishnamurti.org/content/chapter-2
curl -o 03.html https://www.jkrishnamurti.org/content/chapter-3
curl -o 04.html https://www.jkrishnamurti.org/content/chapter-4
curl -o 05.html https://www.jkrishnamurti.org/content/chapter-5
curl -o 06.html https://www.jkrishnamurti.org/content/chapter-6
curl -o 07.html https://www.jkrishnamurti.org/content/chapter-7
curl -o 08.html https://www.jkrishnamurti.org/content/chapter-8
curl -o 09.html https://www.jkrishnamurti.org/content/chapter-9
curl -o 10.html https://www.jkrishnamurti.org/content/chapter-10
curl -o 11.html https://www.jkrishnamurti.org/content/chapter-11
curl -o 12.html https://www.jkrishnamurti.org/content/chapter-12
curl -o 13.html https://www.jkrishnamurti.org/content/chapter-13
curl -o 14.html https://www.jkrishnamurti.org/content/chapter-14
curl -o authors-note.html https://www.jkrishnamurti.org/content/authors-note
curl -o 15.html https://www.jkrishnamurti.org/content/chapter-15
curl -o 16.html https://www.jkrishnamurti.org/content/chapter-16
curl -o 17.html https://www.jkrishnamurti.org/content/chapter-17
curl -o 18.html https://www.jkrishnamurti.org/content/chapter-18
curl -o 19.html https://www.jkrishnamurti.org/content/chapter-19
curl -o 20.html https://www.jkrishnamurti.org/content/chapter-20
curl -o 21.html https://www.jkrishnamurti.org/content/chapter-21
curl -o 22.html https://www.jkrishnamurti.org/content/chapter-22
curl -o 23.html https://www.jkrishnamurti.org/content/chapter-23
curl -o 24.html https://www.jkrishnamurti.org/content/chapter-24
curl -o 25.html https://www.jkrishnamurti.org/content/chapter-25
curl -o 26.html https://www.jkrishnamurti.org/content/chapter-26
curl -o 27.html https://www.jkrishnamurti.org/content/chapter-27